# Tensor 초기화

In [2]:
# import Pytorch, NumPy

import torch
import numpy as np

In [14]:
# 데이터로 directly하게 생성하기

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
# NumPy 배열로부터 생성

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [16]:
# x_np와 np_array는 서로 같은 메모리를 공유하고 있는 것을 알 수 있음
# from_numpy를 통해서 source인 Numpy 배열,
# 이에 대한 리턴 값인 Pytorch 배열
# 원본 데이터인 data는 상관이 없음

x_np[1][1] = 2

print(f'Original Data \n {data} \n')
print(f'torch.tensor(data) \n {x_data} \n')
print(f'np.array(data) \n {np_array} \n')
print(f'torch.from_numpy(np_array) \n {x_np} \n')

Original Data 
 [[1, 2], [3, 4]] 

torch.tensor(data) 
 tensor([[1, 2],
        [3, 4]]) 

np.array(data) 
 [[1 2]
 [3 2]] 

torch.from_numpy(np_array) 
 tensor([[1, 2],
        [3, 2]], dtype=torch.int32) 



* <b>함수들을 써보고 느낀 점은 type이 기본형으로 <code>torch.float32</code>가 들어가지만</b>
* <b>항상 지정해주어야 논리적 오류가 없을 거 같다.</b>

In [20]:
# 다른 텐서로부터 생성하기
# Shape을 그대로 가져간다.
# Type도 따로 지정하지 않는다면, 원래 Tensor 그대로 가져간다.

# rand = 0~1 사이의 숫자를 균등하게 생성
# randn = N(0, 1)인 정규 분포를 따라 추출한 값을 리턴 -> 음수가 나올 수 있다.


x_ones = torch.ones_like(x_data, dtype=torch.float32)
print(f'Ones Tensor: \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype=torch.float32)
print(f'Random Tensor: \n {x_rand} \n')

x_randn = torch.randn_like(x_data, dtype=torch.float32)
print(f'Random N Tensor: \n {x_randn} \n')

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]]) 

Random Tensor: 
 tensor([[0.7524, 0.2504],
        [0.0798, 0.7648]]) 

Random N Tensor: 
 tensor([[-0.6721,  0.1060],
        [-0.1105,  0.7579]]) 



In [7]:
# 무작위(random) or 상수(constant) 값을 사용하기
# shape은 텐서의 차원을 나타내는 튜플로, 아래 함수들에서는 출력 텐서의 차원을 결정

shape = (2, 3,)
rand_tensor = torch.rand(shape)
randn_tensor = torch.randn(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'RandomN Tensor: \n {randn_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor} \n')

Random Tensor: 
 tensor([[0.8905, 0.7969, 0.2240],
        [0.9847, 0.5362, 0.0036]]) 

RandomN Tensor: 
 tensor([[-0.9059,  0.0425, -1.0959],
        [ 0.4511,  0.6399,  0.8163]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor": 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# Tensor의 Attribute

In [24]:
tensor = torch.rand(3, 4, dtype=torch.float32)

print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is store on : {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is store on : cpu


# Tensor의 Operation
* Transposing, indexing, slicing, 수학 계산, 선형 대수, random sampling, 100가지 이상의 Tensor Operation들은 GPU에서 실행시킬 수 있다.
* Colab의 경우 Edit > Notebook Settings에서 GPU 할당 가능
* 기본적으로 텐서는 CPU에 생성되어서 <code>.to</code> 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤) GPU로 텐서를 이동할 수 있다.
* 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이 든다.

In [27]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

print(torch.cuda.is_available())
print(tensor.device)

False
cpu


In [39]:
# NumPy식의 표준 인덱싱과 슬라이싱

tensor = torch.ones(4, 4, dtype=torch.float32)
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:, 0]}')
print(f'Last Column: {tensor[..., -1]}')
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last Column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [40]:
# torch.cat, 텐서합치기

t1 = torch.cat([tensor, tensor, tensor], dim=1)
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [44]:
# Arithmetic operations

# matrix multiplication - y1, y2, y3 모두 같은 값
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# element-wise product - z1, z2, z3 모두 같은 값
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print('<Matrix Multiplication>')
print(y1, y2, y3, sep='\n')

print()

print('<Element Product>')
print(z1, z2, z3)

<Matrix Multiplication>
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

<Element Product>
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [48]:
# Single-element tensor의 aggregate

agg = tensor.sum()
agg_item = agg.item() # scalar value 리턴
print(agg, type(agg), '\n', agg_item, type(agg_item))

tensor(12.) <class 'torch.Tensor'> 
 12.0 <class 'float'>


In [49]:
# in-place 연산

print(f'{tensor} \n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Numpy 변환 (Bridge)
* CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.
* 그럼 만약에 텐서가 GPU에 있고, NumPy가 CPU에 있다면? -> 이런 경우에는 공유 안 됨

In [51]:
arr = np.array([1, 2, 3])
tensor = torch.from_numpy(arr)

if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    
arr[0] = 5
print(torch.cuda.is_available(), arr, tensor)

False [5 2 3] tensor([5, 2, 3], dtype=torch.int32)


In [56]:
# Tensor를 NumPy 배열로 변환하기

t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [57]:
# CPU 상 메모리 공유

t.add_(1)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [58]:
# NumPy 배열을 텐서로 변환하기

n = np.ones(5)
t = torch.from_numpy(n)

In [59]:
# NumPy 배열에서 변경되어도 메모리 공유된다.

np.add(n, 1, out=n)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
